name: Weather Update

on:
  schedule:
    # 이탈리아 시간 기준 00:00, 06:00, 12:00, 18:00 (UTC+1)
    - cron: '0 23,5,11,17 * * *'  # UTC 시간 기준
  workflow_dispatch:  # 수동 실행을 위한 트리거

jobs:
  update-weather:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: Install Chrome and ChromeDriver
      run: |
        # Google Chrome 설치
        wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | sudo apt-key add -
        sudo sh -c 'echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google.list'
        sudo apt-get update
        sudo apt-get install -y google-chrome-stable
        
        # ChromeDriver 설치
        CHROME_VERSION=$(google-chrome --version | awk '{print $3}' | cut -d. -f1,2,3)
        CHROMEDRIVER_VERSION=$(curl -s "https://chromedriver.storage.googleapis.com/LATEST_RELEASE_$CHROME_VERSION")
        wget -q "https://chromedriver.storage.googleapis.com/${CHROMEDRIVER_VERSION}/chromedriver_linux64.zip"
        unzip chromedriver_linux64.zip
        sudo mv chromedriver /usr/local/bin/chromedriver
        sudo chmod +x /usr/local/bin/chromedriver
        
    - name: Run weather update script
      env:
        GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS }}
      run: |
        # credentials.json 파일 생성
        echo "$GOOGLE_CREDENTIALS" > credentials.json
        # 스크립트 실행
        python main.py
        
    - name: Commit and push if changes
      run: |
        git config --local user.email "chjw102@gmail.com"
        git config --local user.name "flowkater"
        git add weather_data_test.csv
        git diff --quiet && git diff --staged --quiet || (git commit -m "Update weather data [skip ci]" && git push) 